import os

try:
    from dotenv import load_dotenv

    load_dotenv()
except ImportError:
    pass


class Env:
    """Environment variables."""

    try:
        BOT_TOKEN = os.environ["BOT_TOKEN"]
    except KeyError:
        raise KeyError("BOT_TOKEN is not set in the environment variables.")

    try:
        APP_ID = os.environ["APP_ID"]
    except KeyError:
        raise KeyError("APP_ID is not set in the environment variables.")

    try:
        APP_HASH = os.environ["APP_HASH"]
    except KeyError:
        raise KeyError("APP_HASH is not set in the environment variables.")

    try:
        REDIS_HOST = os.environ["REDIS_HOST"]
    except KeyError:
        raise KeyError("REDIS_HOST is not set in the environment variables.")

    try:
        REDIS_PORT = int(os.environ["REDIS_PORT"])
    except KeyError:
        raise KeyError("REDIS_PORT is not set in the environment variables.")
    except ValueError:
        raise ValueError("REDIS_PORT is not an integer.")

    try:
        REDIS_PASSWORD = os.environ["REDIS_PASSWORD"]
    except KeyError:
        raise KeyError("REDIS_PASSWORD is not set in the environment variables.")

    try:
        OPENAI_API_KEY = os.environ["OPENAI_API_KEY"]
    except KeyError:
        raise KeyError("OPENAI_API_KEY is not set in the environment variables.")


class Message:

    default_prompt = """You: Hii, who are you?
AI: I am a chatbot. I am here to help you. You can ask me anything. I will try to answer your questions. If ask you to create image from a text query, reply back with a python json "{"action":"image","prompt":query of the image}"
You: """

    start = "Hi, I am a chatbot. I am here to help you. You can ask me anything. I will try to answer your questions. \n\n Created by @AffanTheBest"

    reset = "Your previous queries have been deleted."

    caption = "Generated by @ChatGPTBot"

    caption_image = (
        "Generated by @ChatGPTBot \n\nUse /image command for better experience."
    )

    help = """Thank you for using our Telegram bot. The /help command will provide information about the various features and commands available on our bot. This command will provide a brief overview of each command, as well as steps on how to use them. If you have any questions or need further assistance, please feel free to contact us. Thank you for using our bot and we hope you enjoy it!

Commands: 
/start - Starts a conversation with the bot 
/help - Provides an overview of all the features and commands available 
/image - Generates an image based on your query
/reset - Deletes your previous queries
/terms - Provides information about the terms and conditions of the bot
/about - Provides information about the bot 

We hope this helps you get the most out of our Telegram bot. If you have any questions or need further assistance, please don't hesitate to contact us. Thank you for using our bot and we hope you enjoy it!
    """

    terms = """By using our service, you agree to the following terms and conditions: 

1. You agree to be bound by the Terms of Use, which may be changed from time to time. 

2. You are responsible for ensuring that all information provided is accurate and up to date. 

3. You accept that our service is provided "as is" and we cannot guarantee the accuracy of information provided. 

4. You accept that we are not liable for any damages or losses resulting from the use of our service. 

5. You understand that we may modify the content and services provided at any time without any prior notice. 

6. You accept that all data and information is stored on our servers and is subject to our Privacy Policy. 

7. You agree to use the service only for lawful purposes. 

    """
